Repository gdsc-ssu/sasil-front, pull requests merged in 2022-05, with the labels that each got.

#21 feat: add api utils & login apis
  projects/common/package.json
  projects/common/src/apis/apiUtils.ts
  projects/common/src/apis/auth.ts
  projects/common/src/apis/index.ts
  projects/common/src/apis/user.ts
  projects/common/src/constants/dataTypes.ts
  projects/common/src/constants/index.ts
  projects/common/src/constants/serverInfo.ts
  yarn.lock
Labels: work, common

#19 feat: add login button components
  projects/common/src/constants/index.ts
  projects/common/src/constants/style/color.ts
  projects/common/src/constants/style/index.ts
  projects/common/src/constants/style/textStyles.ts
  projects/common/src/index.ts
  projects/sasil-mobile/App.tsx
  projects/sasil-mobile/assets/fonts/Pretendard-Bold.otf
  projects/sasil-mobile/assets/fonts/Pretendard-Regular.otf
  projects/sasil-mobile/assets/fonts/Pretendard-SemiBold.otf
  projects/sasil-mobile/assets/icons/AppleLogo.tsx
  projects/sasil-mobile/assets/icons/GoogleLogo.tsx
  projects/sasil-mobile/assets/icons/KakaoLogo.tsx
  projects/sasil-mobile/babel.config.js
  projects/sasil-mobile/package.json
  projects/sasil-mobile/react-config.js
  projects/sasil-mobile/src/components/common/atom/StyledText/StyledText.stories.tsx
  projects/sasil-mobile/src/components/common/atom/StyledText/StyledText.tsx
  projects/sasil-mobile/src/components/common/atom/StyledText/index.ts
  projects/sasil-mobile/src/components/common/atom/Test.stories.tsx
  projects/sasil-mobile/src/components/common/atom/Test.tsx
  projects/sasil-mobile/src/components/common/molecule/LoginButton/LoginButton.stories.tsx
  projects/sasil-mobile/src/components/common/molecule/LoginButton/LoginButton.style.ts
  projects/sasil-mobile/src/components/common/molecule/LoginButton/LoginButton.tsx
  projects/sasil-mobile/src/components/common/molecule/LoginButton/index.ts
  projects/sasil-mobile/storybook/index.js
  projects/sasil-mobile/storybook/storyLoader.js
  projects/sasil-mobile/tsconfig.json
  projects/sasil-web/.storybook/main.js
  projects/sasil-web/next.config.js
  projects/sasil-web/package.json
  projects/sasil-web/src/assets/fonts/Pretendard-Bold.otf
  projects/sasil-web/src/assets/fonts/Pretendard-Regular.otf
  projects/sasil-web/src/assets/fonts/Pretendard-SemiBold.otf
  projects/sasil-web/src/assets/icons/AppleLogo.svg
  projects/sasil-web/src/assets/icons/GoogleLogo.svg
  projects/sasil-web/src/assets/icons/KakaoLogo.svg
  projects/sasil-web/src/components/atoms/StyledText/StyledText.stories.tsx
  projects/sasil-web/src/components/atoms/StyledText/StyledText.tsx
  projects/sasil-web/src/components/atoms/StyledText/index.ts
  projects/sasil-web/src/components/common/atom/Test.stories.tsx
  projects/sasil-web/src/components/common/atom/Test.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/LoginButton.stories.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/LoginButton.style.ts
  projects/sasil-web/src/components/molelcules/LoginButton/LoginButton.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/index.ts
  projects/sasil-web/src/constants/styles/global.css
  projects/sasil-web/src/pages/_app.tsx
  projects/sasil-web/tsconfig.json
  yarn.lock
Labels: work

#22 feat: add social-login logics
  projects/common/src/constants/index.ts
  projects/common/src/constants/serverInfo.ts
  projects/sasil-mobile/App.tsx
  projects/sasil-mobile/babel.config.js
  projects/sasil-mobile/package.json
  projects/sasil-mobile/src/components/atom/StyledText/StyledText.stories.tsx
  projects/sasil-mobile/src/components/atom/StyledText/StyledText.tsx
  projects/sasil-mobile/src/components/atom/StyledText/index.ts
  projects/sasil-mobile/src/components/common/molecule/LoginButton/LoginButton.stories.tsx
  projects/sasil-mobile/src/components/molecule/LoginButton/LoginButton.stories.tsx
  projects/sasil-mobile/src/components/molecule/LoginButton/LoginButton.style.ts
  projects/sasil-mobile/src/components/molecule/LoginButton/LoginButton.tsx
  projects/sasil-mobile/src/components/molecule/LoginButton/index.ts
  projects/sasil-mobile/src/components/molecule/LoginButton/social/AppleLoginButton.tsx
  projects/sasil-mobile/src/components/molecule/LoginButton/social/GoogleLoginButton.tsx
  projects/sasil-mobile/src/components/molecule/LoginButton/social/KakaoLoginButton.tsx
  projects/sasil-mobile/src/components/molecule/LoginButton/social/KakaoWebView.tsx
  projects/sasil-mobile/src/components/molecule/LoginButton/social/index.ts
  projects/sasil-mobile/src/components/molecule/LoginButton/social/route.ts
  projects/sasil-mobile/src/components/organisms/auth/SocialLoginBox/SocialLoginBox.stories.tsx
  projects/sasil-mobile/src/components/organisms/auth/SocialLoginBox/SocialLoginBox.style.tsx
  projects/sasil-mobile/src/components/organisms/auth/SocialLoginBox/SocialLoginBox.tsx
  projects/sasil-mobile/src/components/organisms/auth/SocialLoginBox/index.ts
  projects/sasil-mobile/src/routes/RootNavigator.tsx
  projects/sasil-mobile/src/screens/LoginModal/LoginModal.style.tsx
  projects/sasil-mobile/src/screens/LoginModal/LoginModal.tsx
  projects/sasil-mobile/src/screens/LoginModal/index.ts
  projects/sasil-mobile/storybook/storyLoader.js
  projects/sasil-mobile/tsconfig.json
  projects/sasil-mobile/yarn-error.log
  projects/sasil-web/package.json
  projects/sasil-web/src/assets/icons/SasilLogo.svg
  projects/sasil-web/src/components/molelcules/LoginButton/routes.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/social/AppleLoginButton.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/social/GoogleLoginButton.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/social/KakaoLoginButton.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/social/index.ts
  projects/sasil-web/src/components/organisms/auth/SocialLoginBox/SocialLoginBox.stories.tsx
  projects/sasil-web/src/components/organisms/auth/SocialLoginBox/SocialLoginBox.style.tsx
  projects/sasil-web/src/components/organisms/auth/SocialLoginBox/SocialLoginBox.tsx
  projects/sasil-web/src/components/organisms/auth/SocialLoginBox/index.ts
  projects/sasil-web/src/pages/login.tsx
  yarn.lock
Labels: work

#23 feat: add global user state for sasil-web
  projects/sasil-mobile/src/components/molecule/LoginButton/social/AppleLoginButton.tsx
  projects/sasil-mobile/src/components/molecule/LoginButton/social/GoogleLoginButton.tsx
  projects/sasil-mobile/src/components/molecule/LoginButton/social/KakaoWebView.tsx
  projects/sasil-mobile/src/logics/store/actions.ts
  projects/sasil-mobile/src/logics/store/atoms.ts
  projects/sasil-web/package.json
  projects/sasil-web/src/components/molelcules/LoginButton/social/AppleLoginButton.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/social/GoogleLoginButton.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/social/KakaoLoginButton.tsx
  projects/sasil-web/src/logics/store/actions.ts
  projects/sasil-web/src/logics/store/atoms.ts
  yarn.lock
Labels: work

#24 refactor: replace local api with common api
  projects/common/src/apis/auth.ts
  projects/sasil-mobile/src/components/molecule/LoginButton/social/AppleLoginButton.tsx
  projects/sasil-mobile/src/components/molecule/LoginButton/social/GoogleLoginButton.tsx
  projects/sasil-mobile/src/components/molecule/LoginButton/social/KakaoWebView.tsx
  projects/sasil-mobile/src/components/molecule/LoginButton/social/route.ts
  projects/sasil-web/src/components/molelcules/LoginButton/routes.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/social/AppleLoginButton.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/social/GoogleLoginButton.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/social/KakaoLoginButton.tsx
  yarn.lock
Labels: refactor

#28 feat: add post-card components for main-page in Web
  projects/common/src/constants/style/textStyles.ts
  projects/sasil-mobile/package.json
  projects/sasil-web/.storybook/preview.js
  projects/sasil-web/src/assets/icons/Heart.svg
  projects/sasil-web/src/components/atoms/ProfileImage/ProfileImage.stories.tsx
  projects/sasil-web/src/components/atoms/ProfileImage/ProfileImage.tsx
  projects/sasil-web/src/components/atoms/ProfileImage/index.ts
  projects/sasil-web/src/components/atoms/StyledText/StyledText.stories.tsx
  projects/sasil-web/src/components/atoms/StyledText/StyledText.tsx
  projects/sasil-web/src/components/molelcules/Like/Like.stories.tsx
  projects/sasil-web/src/components/molelcules/Like/Like.style.tsx
  projects/sasil-web/src/components/molelcules/Like/Like.tsx
  projects/sasil-web/src/components/molelcules/Like/index.ts
  projects/sasil-web/src/components/molelcules/LoginButton/LoginButton.stories.tsx
  projects/sasil-web/src/components/molelcules/LoginButton/LoginButton.style.ts
  projects/sasil-web/src/components/molelcules/LoginButton/LoginButton.tsx
  projects/sasil-web/src/components/molelcules/WriterInfo/WriterInfo.stories.tsx
  projects/sasil-web/src/components/molelcules/WriterInfo/WriterInfo.style.tsx
  projects/sasil-web/src/components/molelcules/WriterInfo/WriterInfo.tsx
  projects/sasil-web/src/components/molelcules/WriterInfo/index.ts
  projects/sasil-web/src/components/organisms/login/SocialLoginBox/SocialLoginBox.stories.tsx
  projects/sasil-web/src/components/organisms/login/SocialLoginBox/SocialLoginBox.style.tsx
  projects/sasil-web/src/components/organisms/login/SocialLoginBox/SocialLoginBox.tsx
  projects/sasil-web/src/components/organisms/login/SocialLoginBox/index.ts
  projects/sasil-web/src/components/organisms/post/Post.style.tsx
  projects/sasil-web/src/components/organisms/post/Post.tsx
  projects/sasil-web/src/components/organisms/post/PostMiniCard.stories.tsx
  projects/sasil-web/src/components/organisms/post/index.ts
  projects/sasil-web/src/constants/styles/global.css
  projects/sasil-web/src/pages/login.tsx
  yarn.lock
Labels: work

#30 feat: add post-card components for Mobile
  projects/common/.eslintrc
  projects/sasil-mobile/assets/icons/Heart.tsx
  projects/sasil-mobile/package.json
  projects/sasil-mobile/src/components/atom/ProfileImage/ProfileImage.stories.tsx
  projects/sasil-mobile/src/components/atom/ProfileImage/ProfileImage.style.tsx
  projects/sasil-mobile/src/components/atom/ProfileImage/ProfileImage.tsx
  projects/sasil-mobile/src/components/atom/ProfileImage/index.ts
  projects/sasil-mobile/src/components/atom/StyledText/StyledText.stories.tsx
  projects/sasil-mobile/src/components/dummyData.ts
  projects/sasil-mobile/src/components/molecule/Like/Like.stories.tsx
  projects/sasil-mobile/src/components/molecule/Like/Like.style.tsx
  projects/sasil-mobile/src/components/molecule/Like/Like.tsx
  projects/sasil-mobile/src/components/molecule/Like/index.ts
  projects/sasil-mobile/src/components/molecule/WriterInfo/WriterInfo.stories.tsx
  projects/sasil-mobile/src/components/molecule/WriterInfo/WriterInfo.style.tsx
  projects/sasil-mobile/src/components/molecule/WriterInfo/WriterInfo.tsx
  projects/sasil-mobile/src/components/molecule/WriterInfo/index.ts
  projects/sasil-mobile/src/components/organisms/PostCard/PostCard.stories.tsx
  projects/sasil-mobile/src/components/organisms/PostCard/PostCard.style.tsx
  projects/sasil-mobile/src/components/organisms/PostCard/PostCard.tsx
  projects/sasil-mobile/src/components/organisms/PostCard/index.ts
  projects/sasil-mobile/src/components/organisms/login/SocialLoginBox/SocialLoginBox.stories.tsx
  projects/sasil-mobile/src/components/organisms/login/SocialLoginBox/SocialLoginBox.style.tsx
  projects/sasil-mobile/src/components/organisms/login/SocialLoginBox/SocialLoginBox.tsx
  projects/sasil-mobile/src/components/organisms/login/SocialLoginBox/index.ts
  projects/sasil-mobile/src/screens/LoginModal/LoginModal.tsx
  projects/sasil-mobile/storybook/index.js
  projects/sasil-mobile/storybook/storyLoader.js
  projects/sasil-web/src/components/molelcules/LoginButton/LoginButton.tsx
  yarn.lock
Labels: work, mobile
